pull_requests:
  do_not_increment_build_number: true

install:
  - sh: curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin --install-dir /usr/share/dotnet --version 8.0.100

image: Ubuntu

build_script:
  - sh: ./build.sh --target="Default"

test_script:
- sh: cd ./tests/BuildFile && ./build.sh

artifacts:
- path: BuildArtifacts/Package/*.*nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: wRFlMYtosIKJTlSC2q1yT1ah5sUbIPi5+67ZdB8WbS8PduaP64Zj484JoU7dXx2R
  on:
    branch: main
