pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

build_script:
  - ps: ./build.ps1 --Target Pack

test_script:
- sh: cd ./tests/BuildScript && ./build.sh

artifacts:
- path: nuget/*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: wRFlMYtosIKJTlSC2q1yT1ah5sUbIPi5+67ZdB8WbS8PduaP64Zj484JoU7dXx2R
  on:
    branch: main
